[package]
name = "native_wave_synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "native_wave_synth"
crate-type = ["cdylib"]

[dependencies]
